import numpy as np

def eta_S_1(C_a: float,
            c_a: float,
            c_c: float,
            t: float) -> float:
    
    r"""
    The function \eta_{S,1}.

    The function \eta_{S,1} is an upper bound for the operator norm -- with respect to
    the H^1 norm-- of the operators of the C_0 semigroup (S(t))_{t\geq0}, generated by the 
    operator -L^{-1}M:

    |||S(t)|||_1 \leq \eta_{S,1}(t) = \sqrt{C_a/c_a} e^{-\nu t},    with \nu = min{c_c/C_L, c_c/c_a}.

    The operator norm ||| |||_1: B(H^1_0(\Omega)) \to \RR is defined by 

    |||A|||_1 = \max{||u||_{1,\Omega}} ||Au||_{1,\Omega},

    where || ||_{1,\Omega} denotes the H^1 norm on H^1_0(\Omega).

    Args:
    C_a: float 
        Boundedness constant of the bilinear form a.
    
    c_a: float 
        Coercivity constant of the bilinear form a.
    
    c_c: float 
        'Coercivity' constant of the bilinear form c.
    
    t: float 
        The time variable t.

    Returns
    -------
    :float 
        \eta_{S,1} evaluated at t.          
    """

    # The value \nu
    nu = np.min(np.array([c_c/C_a, c_c/c_a]))

    return(np.sqrt(C_a/c_a)*np.exp(nu*t))