import numpy as np

def eta_S_star_2(M_2_star: float,
                 omega_2_star: float,
                 t: float) -> float:
    
    r"""
    The function \eta_{S_*,2}.

    The function \eta_{S_*,2} is an upper bound for the operator norm -- with respect to
    the H^1 norm-- of the operators of the C_0 semigroup (S(t))_{t\geq0}, generated by the 
    operator -L^{-1}M^*:

    |||S(t)|||_2 \leq \eta_{S,1}(t) = M_{2,*} e^{\omega_{2,*} t},   

    The operator norm ||| |||_2: B(H^2(\Omega)) \to \RR is defined by 

    |||A|||_2 = \max{||u||_{2,\Omega}} ||Au||_{2,\Omega},

    where || ||_{2,\Omega} denotes the H^2 norm on H^2(\Omega).

    Parameters
    ----------
    M_2_star: float 
        Generic constant M_{2,*}
    
    omega_2_star: float 
        Generic constant M_{2,*}
    
    t: float 
        The time variable t.

    Returns
    -------        
    :float 
        \eta_{S_*,2} evaluated at t.          
    """

    return(M_2_star * np.exp(omega_2_star * t))