import numpy as np

from ..pseudo_parabolic_pde_class import PseudoParabolicPDE


def _eta_S_1(pde: PseudoParabolicPDE,
             t: float) -> float:

    r""" The function \eta_{S,1}, an upper bound for the operator norm -- with
    respect to the H^1 norm -- of the operators of the C_0 semigroup
    (S(t))_{t\geq0}, generated by the operator -L^{-1}M:

        |||S(t)|||_1 \leq \eta_{S,1}(t) = \sqrt{C_a/c_a} e^{\nu t},    with \nu = min{c_c/C_a, c_c/c_a}.

    Args:
        pde (PseudoParabolicPDE): The pseudo-parabolic PDE, providing the
            generic constants C_a, c_a and c_c.
        t (float): The time variable t.

    Returns:
        float: \eta_{S,1} evaluated at t.
    """

    C_a, c_a, _, c_c, _, _, _, _ = pde.generic_constants

    # The value \nu
    nu = np.min(np.array([c_c/C_a, c_c/c_a]))

    return float(np.sqrt(C_a/c_a) * np.exp(nu*t))


def _eta_S_star_2(pde: PseudoParabolicPDE,
                  t: float) -> float:

    r""" The function \eta_{S_*,2}, an upper bound for the operator norm --
    with respect to the H^2 norm -- of the operators of the C_0 semigroup
    (S(t))_{t\geq0}, generated by the operator -L^{-1}M^*:

        |||S(t)|||_2 \leq \eta_{S_*,2}(t) = M_{2,*} e^{\omega_{2,*} t}.

    Args:
        pde (PseudoParabolicPDE): The pseudo-parabolic PDE, providing the
            generic constants M_{2,*} and \omega_{2,*}.
        t (float): The time variable t.

    Returns:
        float: \eta_{S_*,2} evaluated at t.
    """

    _, _, _, _, M_2_star, omega_2_star, _, _ = pde.generic_constants

    return float(M_2_star * np.exp(omega_2_star * t))


def _sigma_j(pde: PseudoParabolicPDE,
             t_j: float,
             t_jm1: float) -> float:

    r""" The value \sigma_j = max{\eta_{S,1}(T-t_j), \eta_{S,1}(T-t_{j-1})}.

    Args:
        pde (PseudoParabolicPDE): The pseudo-parabolic PDE, providing the
            final time T and the generic constants C_a, c_a and c_c.
        t_j (float): The time t_j.
        t_jm1 (float): The time t_{j-1}.

    Returns:
        float: The value \sigma_j.
    """

    T = pde.final_time

    return max(_eta_S_1(pde, T-t_j), _eta_S_1(pde, T-t_jm1))


def _mu_j(pde: PseudoParabolicPDE,
          t_j: float,
          t_jm1: float) -> float:

    r""" The value \mu_j = max{\eta_{S_*,2}(T-t_j), \eta_{S_*,2}(T-t_{j-1})}.

    Args:
        pde (PseudoParabolicPDE): The pseudo-parabolic PDE, providing the
            final time T and the generic constants M_{2,*} and \omega_{2,*}.
        t_j (float): The time t_j.
        t_jm1 (float): The time t_{j-1}.

    Returns:
        float: The value \mu_j.
    """

    T = pde.final_time

    return max(_eta_S_star_2(pde, T-t_j), _eta_S_star_2(pde, T-t_jm1))
